
server_address ="smtp.gmail.com"
port = 587

sender_mail="sender mail"
password="password"
to_mail = 'reciever mail'

subject = "Python Test mail"

message = "Dear user\n\nThank you for your mail we will get back to you soon.\n\nThis is an Autogenerated mail don't repay to this mail"
